### ISSUE TITLE
netman_watch_dns.c compilation error

### ISSUE THREAD

**Issue by anoo1** [openbmc/phosphor-networkd#16]
This PR causes openbmc to fail to compile: https://github.com/openbmc/phosphor-networkd/pull/13

Log data follows:                                                                                         
| DEBUG: Executing shell function do_compile                                                              
| NOTE: make -j 24 -e MAKEFLAGS=                                                                          
| arm-openbmc-linux-gnueabi-gcc  -march=armv5e -marm  -mthumb-interwork --sysroot=/tmp/anoo/obmc/barreleye/build/tmp/sysroots/barreleye  -O2 -pipe -g -feliminate-unused-debug-types   -c -o netman_watch_dns.o netman_watch_dns.c                                                                                            
| netman_watch_dns.c:8:28: fatal error: systemd/sd-bus.h: No such file or directory                       
|  #include <systemd/sd-bus.h>                                                                            
|                             ^                                                                           
| compilation terminated.                                                                                 
| make: *** [netman_watch_dns.o] Error 1

**Comment by anoo1** [comment]
@vishwabmc could you take a look?

**Comment by vishwabmc** [comment]
Hmm.. This is interesting.. I have compiled and tested this enough times and all went well. I will see what this is.

**Comment by anoo1** [comment]
More updates being integrated including recipe update, closing this issue for now.
