### ISSUE TITLE
Issue with changing MACAddress for interface other than eth0

### ISSUE THREAD

**Issue by vincentto13** [openbmc/phosphor-networkd#21]
When changing interface MACAddress over DBus property. The mac is being set correctly for eth0, but setting MAC for any other (i.e. eth1) will override MAC for eth0 after platform reboot. The issue is in ethernet_interface.cpp:701 file, and function:

```
std::string EthernetInterface::mACAddress(std::string value)
```

executes

```
execute("/sbin/fw_setenv", "fw_setenv", "ethaddr", value.c_str());
```

without differentiation on interface it's changing. There shall be the following mapping
```
"ethaddr" -> will change eth0 MACAddress
"eth1addr" -> will change eth1 MACAddress
...
```

Regards,
Pawel

**Comment by amboar** [comment]
@vincentto13 Thanks for the bug report. Any chance you could submit a patch? FWIW patches go through the project's Gerrit instance at https://gerrit.openbmc-project.xyz/.

**Comment by ratagupt** [comment]
This has been fixed 
https://github.com/openbmc/phosphor-networkd/blob/master/src/ethernet_interface.cpp#L1178

Earlier it was hardcoded, now this has been fixed, closing this defect.
