### ISSUE TITLE
networkd confuses default route vs. gateway, and creates useless route

### ISSUE THREAD

**Issue by jk-ozlabs** [openbmc/phosphor-networkd#22]
phosphor-networkd seems to have a confused view of separate "gateway" and "default route" concepts, which should be the same thing (at least on non-router hosts, which the BMC should be).

The dbus interfaces specify a per-interface "Gateway", and there's also a system-wide "DefaultGateway". This doesn't make any sense though, as the per-interface Gateway is just the gateway for packets not local to that interface's network (ie, not within the netmask), so is exactly the same as the default gateway.

Then, this means that the systemd-networkd config has a useless `[Route] ` section:

```
root@witherspoon:~# cat /etc/systemd/network/00-bmc-eth0.network  
[Match]
Name=eth0
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=false
DHCP=false
Address=9.3.185.161/23
Gateway=9.3.185.1
[Route]
Gateway=9.3.185.1
Destination=9.3.184.0
```
The actual default route is being created by the `Gateway` configuration in the `[Network]` section. The `[Route]` section there specifies this route:

```
9.3.184.0 via 9.3.185.1 dev eth0
```

\- which makes no sense: it's a host route for a non-host address.

We have two options to correct this:

 - Drop the concept of having a per-interface gateway, and just use the one on the SystemConfiguration interface.
 - Drop the system-wide `DefaultGateway` on SystemConfiguration interface, but allow per-interface Gateways to be empty

The former probably makes a lot more sense. Either way, we don't need the `.network` configuration to specify both `[Route]` and `[Network].Gateway`. If we use `[Route]`, we should fix it so it actually creates a proper default route.

In situations where we have multiple interfaces, the route/gateway config would only apply to one device.

**Comment by edtanous** [comment]
I would've thought the second solution (dropping DefaultGateway) would make more sense for a BMC.

Consider the case where I have multiple NICs on completely redundant networks, with independent gateways.  If one of the NICs goes down, and the DefaultGateway is now outside of accessible the subnet range, or set to a NIC that is no longer connected, what happens to the routes if I only have one gateway defined?

I don't know the systemd network configuration well enough to say what the right answer is here, but I'm not sure we can drop support for per-interface gateways without some kind of fallout from the people that need it for failover.

Looking @jk-ozlabs explanation above, doesn't that just mean we need to properly set up the route?  Given that example, something like:
[Match]
Name=eth0
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=false
DHCP=false
Address=9.3.185.161/23
[Route]
Gateway=9.3.185.1
Destination=9.3.185.0/8
Metric=100

I've also added metric, as it seems important to be able to specify if we a route per interface.  Although I'm not sure if it's available through the existing DBus interfaces today.

Most of what precedes this is just guessing.  I only got pulled into this from a webui patch that was deleting the gateway field, and I followed the breadcrumbs here.  I fully defer to the systemd experts here on how to properly set up per-interface gateways, but I think it's important as a system level feature.

**Comment by ratagupt** [comment]
@jk-ozlabs @edtanous : We have fixed this issue through the following commit where we choose to go with option 2
       Drop the system-wide DefaultGateway on SystemConfiguration interface, but allow per-interface Gateways to be empty

Now the phosphor-networkd is not using the gateway from the system configuration interface, However the gateway  is there in the ethernet interface.
https://github.com/openbmc/phosphor-networkd/commit/a5a0944ccb8d925d6d83897b1e2397e85564ea1e
https://github.com/openbmc/phosphor-networkd/commit/252feec6fea76a31ee89d984713067ad53cd9bd6

**Comment by ratagupt** [comment]
@jk-ozlabs : I am closing this defect as it is fixed.
