### ISSUE TITLE
when multiple DNS servers are sent in DHCP response BMC will have only 1 entry

### ISSUE THREAD

**Issue by prkatti1** [openbmc/phosphor-networkd#28]
when multiple DNS servers are sent in DHCP response BMC will have only 1 entry in the /etc/resolv.conf

if we send 3 nameservers in dhcp response like:
```
xx.xx.xx.xx
yy.yy.yy.yy
zz.zz.zz.zz 
```

BMC should get configured with 3 nameservers ie resolv.conf should have 3 entries:
```
nameserver xx.xx.xx.xx
nameserver yy.yy.yy.yy
nameserver zz.zz.zz.zz
```

But resolv.conf has only 1 entry like:
```
nameserver xx.xx.xx.xx yy.yy.yy.yy zz.zz.zz.zz
```

So it is resulting into wrong configuration and unusable configuration.

**Comment by ratagupt** [comment]
@prkatti1 : Can we close this issue? Seems it is fixed and we kept it open.

**Comment by prkatti1** [comment]
Yeah it got fixed, closing this.
