### ISSUE TITLE
NTP server that is configured via DHCP, is not shown in redfish command

### ISSUE THREAD

**Issue by ratagupt** [openbmc/phosphor-networkd#30]
This issue is same as issue https://github.com/openbmc/phosphor-networkd/issues/29
Here the same changes need to make for the NTP server.

**Comment by sunharis** [comment]
@asmithakarun has a fix for this at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/50156

**Comment by sunharis** [comment]
This issue is fixed. Both static and dynamic NTP servers are stored separately and are displayed at redfish GET command. This can be closed @ratagupt
