### ISSUE TITLE
OpenBMC networking doesn't respect RFC3927 - Autoconfigured Link-Local address issue

### ISSUE THREAD

**Issue by tajudheenk** [openbmc/phosphor-networkd#32]
As per RFC 3927, the network auto-configuration IP address (169.254/16 prefix) should be assigned only when interface is configured in DHCP mode and no routable ip address is assigned to the interface. If DHCP is present and replied to the IP address request, the interface should only keep the given DHCP IP address.

Also, if we start with an auto-configuration address and then modify the interface parameter to give a fixed IP address, the auto-configuration address should be removed.

**Comment by ratagupt** [comment]
@tajudheenk , We were working on the same and we find that systemd-networkd requires more changes to achieve the same.

Please find the discussion below.
https://github.com/systemd/systemd/issues/13316

**Comment by tajudheenk** [comment]
@ratagupt It seems systemd/systemd#13316 is now closed. Is this change included in OpenBMC 2.9 as we have newer version of systemd?
