### ISSUE TITLE
getNameServerFromResolvd function can't parse IPv6 nameserver address in right way

### ISSUE THREAD

**Issue by Fanysh** [openbmc/phosphor-networkd#34]
When I have a nameserver 2001:db8:1::1 in /etc/resolv.conf, the Nameservers interface will show it as "32.1.13.184.0.1.0.0.0.0.0.0.0.0.0.1"

**Comment by AlexanderAmelkin** [comment]
Please see https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/40378
