### ISSUE TITLE
Endless cycle in toV6Cidr function

### ISSUE THREAD

**Issue by Kitsok** [openbmc/phosphor-networkd#36]
If by whatsoever reason toV6Cidr functions gets /128 mask (ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff), it fails into endless cycle.

Here is the log:
%%
toCidr
toV6Cidr subnetmask:ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
toV6Cidr In cycle cidr=0 pos=0 prevPos=0
toV6Cidr In cycle cidr=16 pos=4 prevPos=5
toV6Cidr In cycle cidr=32 pos=9 prevPos=10
toV6Cidr In cycle cidr=48 pos=14 prevPos=15
toV6Cidr In cycle cidr=64 pos=19 prevPos=20
toV6Cidr In cycle cidr=80 pos=24 prevPos=25
toV6Cidr In cycle cidr=96 pos=29 prevPos=30
toV6Cidr In cycle cidr=112 pos=34 prevPos=35
toV6Cidr In cycle cidr=128 pos=255 prevPos=0
toV6Cidr In cycle cidr=144 pos=4 prevPos=5
toV6Cidr In cycle cidr=160 pos=9 prevPos=10
toV6Cidr In cycle cidr=176 pos=14 prevPos=15
toV6Cidr In cycle cidr=192 pos=19 prevPos=20
toV6Cidr In cycle cidr=208 pos=24 prevPos=25
toV6Cidr In cycle cidr=224 pos=29 prevPos=30
toV6Cidr In cycle cidr=240 pos=34 prevPos=35
toV6Cidr In cycle cidr=0 pos=255 prevPos=0
toV6Cidr In cycle cidr=16 pos=4 prevPos=5
toV6Cidr In cycle cidr=32 pos=9 prevPos=10
toV6Cidr In cycle cidr=48 pos=14 prevPos=15
toV6Cidr In cycle cidr=64 pos=19 prevPos=20
toV6Cidr In cycle cidr=80 pos=24 prevPos=25
toV6Cidr In cycle cidr=96 pos=29 prevPos=30
%%

I will fix it and post here diff.

**Comment by Kitsok** [comment]
Here is quick fix

diff --git a/util.cpp b/util.cpp
index cb9e720..2cf1ba7 100644
--- a/util.cpp
+++ b/util.cpp
@@ -43,6 +43,9 @@ uint8_t toV6Cidr(const std::string& subnetMask)
     uint16_t buff{};
     do
     {
+        if (cidr >= 128)
+            return 128;
+
         // subnet mask look like ffff:ffff::
         // or ffff:c000::
         pos = subnetMask.find(":", prevPos);

**Comment by leiyu-bytedance** [comment]
This issue is fixed by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/40192, @Kitsok please verify and close.

**Comment by Kitsok** [comment]
Works for me, thank you!
