### ISSUE TITLE
Default gateway missing when multiple gateway are configured

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/phosphor-networkd#40]
As described in Discord https://discord.com/channels/775381525260664832/775381525260664836/872053482222411847, `phosphor-networkd` creates multiple gateways and cause the default gateway missing.

```
   1     auto gateway = EthernetInterfaceIntf::defaultGateway();
   2     if (!gateway.empty())
   3     {
   4         stream << "[Route]\n";
   5         stream << "Gateway=" << gateway << "\n";
   6     }
   7
   8     auto gateway6 = EthernetInterfaceIntf::defaultGateway6();
   9     if (!gateway6.empty())
  10     {
  11         stream << "[Route]\n";
  12         stream << "Gateway=" << gateway6 << "\n";
  13     }
  14
  15     if (manager.getSystemConf())
  16     {
  17         const auto& gateway = manager.getSystemConf()->defaultGateway();
  18         if (!gateway.empty())
  19         {
  20             stream << "[Route]\n";
  21             stream << "Gateway=" << gateway << "\n";
  22         }
  23         const auto& gateway6 = manager.getSystemConf()->defaultGateway6();
  24         if (!gateway6.empty())
  25         {
  26             stream << "[Route]\n";
  27             stream << "Gateway=" << gateway6 << "\n";
  28         }
  29     }
```
The above code snippet could result in below network config:
```
[Address]
Address=<my correct ipv6>/64
[Route]
Gateway=<a correct gateway with link-local-address>
[Route]
Gateway=<another correct gatway with ipv6>
```

The behavior happens when the BMC gets an IPv6 address/gateway from the DHCP server, and then the user sets the static IPv6 address and gateway.

**Comment by leiyu-bytedance** [comment]
This issue could be fixed by dropping the code of `if (manager.getSystemConf())`, so it always write gateway config from the DBus config.

**Comment by ratagupt** [comment]
Multiple default gateways can exist on the system , why this is an issue?
However there is a plan to deprecate the system config gateway as we have introduced the gateway in the ethernet interface already.
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Network/EthernetInterface.interface.yaml#L80

@raviteja-b : where we are on this to remove the gateway from system configuration interface? I remember you were working on this.
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Network/SystemConfiguration.interface.yaml#L11

**Comment by leiyu-bytedance** [comment]
> Multiple gateways can exist on the system , why this is an issue?

See https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/45634 for the description.

In short, with multiple gateways (IPv6 in my case), there is no default gateway anymore. The `DefaultGateway6` on DBus becomes empty, and ipmitool lan6 print shows empty default gateway.

**Comment by ratagupt** [comment]
@leiyu-bytedance : System config is also an Dbus object where the gateway is there for the Ipv4 also. We can not just remove it as it is.
> In short, with multiple gateways (IPv6 in my case), there is no default gateway anymore. The DefaultGateway6 on DBus becomes empty, and ipmitool lan6 print shows empty default gateway.

**Comment by ratagupt** [comment]
@wak-google any views here^^^^

**Comment by wak-google** [comment]
I think we need to fix all of the other client code to ensure it is using the per-interface settings first.

**Comment by leiyu-bytedance** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-ipmid/+/45806
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/45634
@wak-google The above patches should fix the issue.
