### ISSUE TITLE
Failed to set static ip after setting the ipsrc to static from dhcp

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/phosphor-networkd#41]
This issue could be reproduced in QEMU.

When the image is started in QEMU, it gets DHCP IP/gateway correctly, e.g.
```
ipmitool lan print
...
IP Address Source       : DHCP Address
IP Address              : 10.0.2.15
Subnet Mask             : 255.255.255.0
MAC Address             : 52:54:00:12:34:56
Default Gateway IP      : 10.0.2.2
...
```

Now let's set the static IP with the below IPMI commands:
```
ipmitool lan set 1 ipsrc static
ipmitool lan set 1 ipaddr 10.0.2.15
ipmitool lan set 1 netmask 255.255.255.0
ipmitool lan set 1 defgw ipaddr 10.0.2.2
```

It fails to set the IP address because of the below error:
```
Aug 11 02:30:36 romulus phosphor-network-manager[276]: Tried to delete a non-static address
Aug 11 02:30:36 romulus phosphor-network-manager[276]: The operation failed internally.
Aug 11 02:30:36 romulus ipmid[299]: Handler failed to catch exception
```

If we add a long delay (e.g. 10s) between the `ipsrc static` and `ipaddr`, it works fine.

**Comment by ratagupt** [comment]
@leiyu-bytedance If IPMI doesn't cache all the network configuration properties and start updating one by one to the networkd, we may hit the issue as during second update systemd-networkd is getting restarted or dbus objects are getting refreshed.
So IPMI should cache all the network configuration and then send the networkd to apply it once.
or between two commands the time gap should not be more then 7 sec. as the refreshing of the dbus objects in networkd happens after 8 sec.

Can you try reducing the gap between two cmds and try?

**Comment by leiyu-bytedance** [comment]
> Can you try reducing the gap between two cmds and try?

Yup, if I add 5s delay between `ipsrc static` and `ipaddr`, the issue remains.

And I added some traces, the issue occurs at https://github.com/openbmc/phosphor-host-ipmid/blob/master/transporthandler.cpp#L354 that it throws `org.freedesktop.DBus.Error.FileExists` exception.

The exception related to `Tried to delete a non-static address` is already handled in `deleteObjectIfExists()`: https://github.com/openbmc/phosphor-host-ipmid/blob/master/transporthandler.cpp#L321

**Comment by leiyu-bytedance** [comment]
It looks like the object path becomes the same for the DHCP one and the static one.
And because the DBus object of the DHCP one could not be removed, the static one gets the above exception.

**Comment by leiyu-bytedance** [comment]
Tried to add "origin" as an input parameter to the `generateId()` and the issue could be fixed.

**Comment by leiyu-bytedance** [comment]
Sent https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/45801 as the fix
