### ISSUE TITLE
Failed to set IPv6 DHCP from static config

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/phosphor-networkd#43]
This issue could be reproduced in QEMU.

When the BMC is set with IPv6 static IP/gateway, and then set to DHCP, it fails with the below error:
```
systemd-networkd[459]: eth0: Could not set route: No route to host 
systemd-networkd[459]: eth0: Failed 
```

This is because the IPv6 gateway is in the network config, e.g. 
```
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=true
DHCP=true
[Route] 
Gateway=xxx
[DHCP]
ClientIdentifier=mac
UseDNS=true
UseNTP=true
UseHostname=true
SendHostname=true
```

The `systemd-networkd` fails to set the route in the DHCP case.

When DHCP is enabled, the network config shall not write the Gateway.

**Comment by leiyu-bytedance** [comment]
Sent the fix to https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/45845/1

**Comment by Journey-x** [comment]
> Sent the fix to https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/45845/1

Using systemd v253.1 and linux kernel 6.1.15-ea948fd, this issue still exists；

The latest code：
https://github.com/openbmc/phosphor-networkd/blob/1f0052f8e783801288e6701e7b7fd34454a04a3c/src/ethernet_interface.cpp#L717

When the BMC is set with IPv6 static IP/gateway， the network config, e.g.
[DHCPv4]
SendHostname=false
UseHostname=false
UseNTP=false
UseDomains=false
UseDNS=false
[DHCP]
IAID=0xcfaa8471
ClientIdentifier=mac
[IPv6AcceptRA]
DHCPv6Client=false
[DHCPv6]
UseHostname=false
UseNTP=false
UseDomains=false
UseDNS=false
[Network]
Gateway=70.176.0.1
Gateway=70:176::dd:1
Address=70.176.77.28/16
Address=70:176::dd:470a/64
Domains=it.bmctest.com
NTP=70.176.77.28
NTP=70.176.77.193
DHCP=false
IPv6AcceptRA=false
IPVersion=IPv4AndIPv6
DNS=70.176.77.28
DNS=
DNS=
LinkLocalAddressing=ipv6
[Link]
MACAddress=fc:73:fb:d1:4f:90
[Match]
Name=eth0
