### ISSUE TITLE
Bad routing table - Duplicate entries.

### ISSUE THREAD

**Issue by hashtag-amar** [openbmc/phosphor-networkd#44]
With DHCP enabled on either of the network interface, we see multiple duplicate entries in the route table. These entries may sometimes differ by their metric values and some time even those are same as well. 

![OpenBMC issue](https://user-images.githubusercontent.com/36621953/130077338-cf363fb1-ad94-4045-86c7-622eb0097bd5.png)

This may create a problem while finding the most  suitable default route. Manually deleting the one not required can an option but this duplication at first place leads to a bad routing table. 

The routing table should be better managed.

**Comment by ratagupt** [comment]
@hashtag-amar : This one is recently fixed up(around day or two days back) through following commit.
https://github.com/openbmc/phosphor-networkd/commit/cb2d408387eb58b83c90f7c4318e9af0b43298af

Currently openbmc/openbmc master is pointing at this commit https://github.com/openbmc/openbmc/blob/master/meta-phosphor/recipes-phosphor/network/phosphor-network_git.bb#L14

we need to bump up the networkd in openbmc/openbmc to point to the latest commit which should solve your problem.

**Comment by hashtag-amar** [comment]
Thanks for updating  @ratagupt

**Comment by ratagupt** [comment]
@hashtag-amar : If you have tested the fix, Please update here and close the defect.

**Comment by hashtag-amar** [comment]
This fix works good. Hence, I am closing the issue here.
