### ISSUE TITLE
BMC does not throw error on configuring some invalid MAC address

### ISSUE THREAD

**Issue by swe12345** [openbmc/phosphor-networkd#46]
Pre condition:
MAC address length is 6 bytes each byte is hex value and is seperated by Colon ':'
Example: AA:AA:AA:AA:AA:AA
MAX value in each byte is FF

User entering 7 or more bytes of MAC address is invalid MAC address
User trying to configure value more than FF in any of the BYTE is Invalid MAC

Steps to recreate the issue:

Configure 7 bytes MAC address
value= AA:AA:AA:AA:AA:AA:BB

using the curl command
curl -k -H "X-Auth-Token:$bmc_token" PATCH -d '{'MACAddress': 'AA:AA:AA:AA:AA:AA:BB'}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth1

Configure out of range MAC address.(Any of the byte having value more than FF)
value= AA:AA:AA:AA:AA:100
curl -k -H "X-Auth-Token:$bmc_token" PATCH -d '{'MACAddress': 'AA:FF:FF:FF:FF:100'}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth1

In scenario 1: BMC is not validating MAC address, it is truncating last byte and assigning to BMC
In scenario 2: BMC is not validating MAC address, it is truncating last bit from each byte and assigning it to BMC.

Expected results:
It should throw an error, instead of setting MAC address.

**Comment by swe12345** [comment]
@ratagupt @sunharis

**Comment by raviteja-b** [comment]
Mac address validation done as per ether_ntoa_r()

do we need to add any extra checks @ratagupt @wak-google

**Comment by prkatti1** [comment]
looks to me if MAC address entered by user is more than accepted length(6 bytes or 48 bits), it is straight forward error scenario. And appears wrong if system(BMC) alters MAC address entered by user. I may be wrong.
Pls share your opinion and let know whether this is expected behavior or need a fix @ratagupt @wak-google

**Comment by ratagupt** [comment]
I think it should be fine as it takes the first 48 bits and applies that on the system. @wak-google do you have some other view?

**Comment by swe12345** [comment]
@wak-google Can you please confirm about the behaviour.

**Comment by wak-google** [comment]
We could probably parse for this, might be worth just ditching ether_ntoa if we want this kind of validation.

**Comment by wak-google** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/57631

**Comment by swe12345** [comment]
@wak-google On giving out of range MAC address, not getting any error and the MAC address is not getting assigned also.

**Comment by prkatti1** [comment]
Is BMC sending successful or 2xx message for invalid MAC addresses @swe12345 ??

**Comment by swe12345** [comment]
@prkatti1 2xx message is coming on patching the out of range MAC address but the out of range MAC address is not getting assigned.
