### ISSUE TITLE
BMC is not using NTP server/s sent by DHCP server

### ISSUE THREAD

**Issue by swe12345** [openbmc/phosphor-networkd#49]
BMC is not using NTP server/s sent by DHCP server

Enable UseNTPServer dhcp property by using following command
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"DHCPv4" : {"UseNTPServers":true}}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1

Check whether property is set or no using following command:
curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET  https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1

Send DHCP request and see if bmc uses ntp server sent by BMC:
curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET  https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol

**Comment by sunharis** [comment]
https://github.com/openbmc/phosphor-networkd/issues/30 is same.

**Comment by sunharis** [comment]
@asmithakarun has a fix for this at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/50156

**Comment by sunharis** [comment]
@swe12345 Please check and close this. This is already fixed and the commits are merged upstream
