### ISSUE TITLE
Didn't find service unit 'ncsi-netlink.service'

### ISSUE THREAD

**Issue by OguzhanCaglar** [openbmc/phosphor-networkd#50]
Hi

I try to build my machine but at %95 it give me some problems. 

ERROR: phosphor-network-1.0+gitAUTOINC+5dad2aafbc-r1 do_package: Didn't find service unit 'ncsi-netlink.service', specified in SYSTEMD_SERVICE:phosphor-network. 

ERROR: Logfile of failure stored in: /home/pavo/oguz/hs2500yocto/openbmc/build/hs2500/tmp/work/arm1176jzs-openbmc-linux-gnueabi/phosphor-network/1.0+gitAUTOINC+5dad2aafbc-r1/temp/log.do_package.2935

ERROR: Task (/home/pavo/oguz/hs2500yocto/openbmc/meta-phosphor/recipes-phosphor/network/phosphor-network_git.bb:do_package) failed with exit code '1'

I tried to change the path of ncsi service in phosphor-network_git.bb but the problem is keeping.

Can anyone help me?

**Comment by ratagupt** [comment]
@OguzhanCaglar : How you are building, I am not sure but your yocto meta-layer should provide the ncs-nelink.service file.
https://github.com/openbmc/openbmc/tree/master/meta-ibm/recipes-phosphor/network/network/ibm-ac-server

**Comment by OguzhanCaglar** [comment]
yes , my layer has already the file. in meta-hdsc/meta-hs2500/recipes-phosphor/network

**Comment by OguzhanCaglar** [comment]
> @OguzhanCaglar : Your yocto meta-layer should provide the ncs-nelink.service file. https://github.com/openbmc/openbmc/tree/master/meta-ibm/recipes-phosphor/network/network/ibm-ac-server

yes , my layer has already the file. in meta-hdsc/meta-hs2500/recipes-phosphor/network
