### ISSUE TITLE
After host reboot, eth0 source switch from DHCP to static IP 

### ISSUE THREAD

**Issue by Jordan-Chang1** [openbmc/phosphor-networkd#54]
Hello, 
   I have implemented the OpenBMC project with my own platform, and I encountered the problem with network lost after host reboot. The IP before reboot was 192.168.165.28, but however after host reboot the IP became 169.254.51.250. Therefore, I compared the content at `/etc/systemd/network/00-bmc-eth0.network`. The difference was list below. I am wondering why this happen and which deamon causing the IP source changed?

- Before host reboot
```
[Match]
Name=eth0
[Link]
MACAddress=e8:c5:7a:00:cc:02
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=false
DHCP=ipv4
[IPv6AcceptRA]
DHCPv6Client=false
[DHCP]
ClientIdentifier=mac
UseDNS=true
UseDomains=true
UseNTP=true
UseHostname=true
SendHostname=true
```

- After host reboot
```
Name=eth0
[Link]
MACAddress=e8:c5:7a:00:cc:02
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=false
DHCP=false
[IPv6AcceptRA]
DHCPv6Client=false
[Route]
Gateway=192.168.160.1
[DHCP]
ClientIdentifier=mac
UseDNS=true
UseDomains=true
UseNTP=true
UseHostname=true
SendHostname=true
```

Best Regards.

**Comment by OguzhanCaglar** [comment]
Did you solve this problem?

**Comment by wak-google** [comment]
Please retry this against newer code. I believe I made some changes to improve this behavior but more testing will confirm.
