### ISSUE TITLE
No IPv4/IPv6 address in RedFish after certain phosphor-network commit

### ISSUE THREAD

**Issue by Kitsok** [openbmc/phosphor-networkd#62]
After commit 59e5b91d9784274d1d99b4c10e939c38606efacc the generated Dbus tree changed from 
`└─/xyz
  └─/xyz/openbmc_project
    └─/xyz/openbmc_project/network
      ├─/xyz/openbmc_project/network/config
      │ └─/xyz/openbmc_project/network/config/dhcp
      └─/xyz/openbmc_project/network/eth0
        ├─/xyz/openbmc_project/network/eth0/ipv4
        │ └─/xyz/openbmc_project/network/eth0/ipv4/b5383791
        └─/xyz/openbmc_project/network/eth0/ipv6
          ├─/xyz/openbmc_project/network/eth0/ipv6/adfb863b
          └─/xyz/openbmc_project/network/eth0/ipv6/b2c9a25`
to
`-/xyz
  -/xyz/openbmc_project
    -/xyz/openbmc_project/network
      |-/xyz/openbmc_project/network/config
      |-/xyz/openbmc_project/network/dhcp
      -/xyz/openbmc_project/network/eth0
        |-/xyz/openbmc_project/network/eth0/_310_2e2_2e254_2e245_2f11
        |-/xyz/openbmc_project/network/eth0/_32a02_3a6b8_3a0_3a511_3ab62e_3a99ff_3afeb3_3a63be_2f64
        -/xyz/openbmc_project/network/eth0/_66e80_3a_3ab62e_3a99ff_3afeb3_3a63be_2f64`

This leads to missing IPv6 and IPv4 addresses in RedFish @ /redfish/v1/Managers/bmc/EthernetInterfaces/eth0:

`{
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_6_0.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": true,
    "UseDNSServers": false,
    "UseDomainName": false,
    "UseNTPServers": false
  },
  "DHCPv6": {
    "OperatingMode": "Stateful",
    "UseDNSServers": false,
    "UseDomainName": false,
    "UseNTPServers": false
  },
  "Description": "Management Network Interface",
  "FQDN": "xx-xx-xx-xx-xx-xx",
  "HostName": "xx-xx-xx-xx-xx-xx",
  "IPv4Addresses": [],
  "IPv4StaticAddresses": [],
  "IPv6AddressPolicyTable": [],
  "IPv6Addresses": [],
  "IPv6DefaultGateway": "xxxx::xxxx",
  "IPv6StaticAddresses": [],
  "Id": "eth0",
  "InterfaceEnabled": true,
  "LinkStatus": "LinkUp",
  "MACAddress": "xx:xx:xx:xx:xx:xx",
  "MTUSize": 1500,
  "Name": "Manager Ethernet Interface",
  "NameServers": [
    "xx.xx.xx.xx",
    "xxxx::xxxx"
  ],
  "SpeedMbps": 100,
  "StaticNameServers": [],
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Enabled"
  },
  "VLANs": {
    "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/VLANs"
  }
}`

**Comment by williamspatrick** [comment]
Are you using the latest bmcweb code also?

**Comment by williamspatrick** [comment]
@edtanous - Are you aware of any issues?

**Comment by edtanous** [comment]
Yep. The paths changed in networkd, and bmcweb needed to be updated to the new paths.  Assuming folks test the code in review, this should be fixed shortly.  Would be nice if folks could upstream a test for this so we make sure we have coverage.

**Comment by Kitsok** [comment]
> Are you using the latest bmcweb code also?

Yes, I took the latest commits of both phosphor-network and bmcweb, also I've disabled all our local patches.

**Comment by edtanous** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61189

Is likely the fix you're looking for.  Please test and leave comments if it solves your problem.

**Comment by edtanous** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61189 Was merged a month ago, and I haven't heard of similar failures.  I suspect this bug can be closed.

**Comment by sunharis** [comment]
@Kitsok Can you please check and close this issue?
