### ISSUE TITLE
SLAAC valid lifetime is not getting updated properly

### ISSUE THREAD

**Issue by swe12345** [openbmc/phosphor-networkd#65]
SLAAC valid lifetime is not getting updated properly
If new valid lifetime is lesser than existing remaining lifetime, client should retain higher remaining lifetime value.

SLAA valid lifetime should work as per the below table:
      1.  If the received Valid Lifetime is greater than 2 hours or
          greater than RemainingLifetime, set the valid lifetime of the
          corresponding address to the advertised Valid Lifetime.

      2.  If RemainingLifetime is less than or equal to 2 hours, ignore
          the Prefix Information option with regards to the valid
          lifetime, unless the Router Advertisement from which this
          option was obtained has been authenticated (e.g., via Secure
          Neighbor Discovery [RFC3971]).  If the Router Advertisement
          was authenticated, the valid lifetime of the corresponding
          address should be set to the Valid Lifetime in the received
          option.

      3.  Otherwise, reset the valid lifetime of the corresponding
          address to 2 hours.
          
          
          root@ever28bmc:~# ip addr
          
         1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
         link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet xx.xx.xx.xx/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/16 brd xx.xx.xx.xx scope link eth0
       valid_lft forever preferred_lft forever
    inet xx.xx.xx.xx/24 brd xx.xx.xx.xx scope global eth0
       valid_lft forever preferred_lft forever
    inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/24 brd xx.xx.xx.xx scope global dynamic eth1
       valid_lft 364sec preferred_lft 364sec
    inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope global dynamic noprefixroute flags 100
       valid_lft 9993sec preferred_lft 493sec
    inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope link
       valid_lft forever preferred_lft forever
       
       
root@ever28bmc:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inetxx.xx.xx.xx/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/16 brd xx.xx.xx.xx scope link eth0
       valid_lft forever preferred_lft forever
    inet xx.xx.xx.xx/24 brd xx.xx.xx.xx scope global eth0
       valid_lft forever preferred_lft forever
    inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/24 brd xx.xx.xx.xx scope global dynamic eth1
       valid_lft 584sec preferred_lft 584sec
    inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope global dynamic noprefixroute flags 100
       valid_lft 994sec preferred_lft 494sec
    inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope link
       valid_lft forever preferred_lft forever

**Comment by sunharis** [comment]
@swe12345 Can you please provide the documents or the RFC links which mention about this requirement? 
@wak-google @ratagupt Do you think this is an issue in phosphor-networkd? Per my views, this is at the systemd scope.

**Comment by wak-google** [comment]
This is systemd-networkd, phosphor-networkd does not interact with RAs

**Comment by sunharis** [comment]
@swe12345 please open an issue with systemd-networkd. This can be closed.
